### ISSUE TITLE
Is this a leak of secret?

### ISSUE THREAD

**Issue by ProgramRipper** [OpenL2D/moc3ingbird#1]
It seems that Live2D Inc did not fix this security issue when you published [this post about the details](https://undeleted.ronsor.com/live2d-a-security-trainwreck/) and this repo about reproduction.

Did Live2D Inc failed to or refuse to fix this issue during the confidential period?

Or you are leaking secrets before even giving them any time?

**Comment by Ronsor** [comment]
None of the information contained in this repository should be considered secret.

As for why I went ahead and released this information, I discussed that at https://undeleted.ronsor.com/live2d-why-full-disclosure. There was no confidential period.
