### ISSUE TITLE
cmo3.hexpat缺少关键字段

### ISSUE THREAD

**Issue by 66hh** [OpenL2D/moc3ingbird#5]
struct FileInfo {
    StringSlice fileName;
    ByteSlice tag;
    // padding[8];
    u64 dataOffset [[CRYPT_U64]];
    u32 fileSize [[CRYPT_U32]];
    bool isObfuscated [[CRYPT_BOOL]];
    u8 compression [[CRYPT_U8]];
    padding[8];
};

**Comment by Ronsor** [comment]
The pattern file is incomplete. For a correct parser, see https://github.com/wader/fq/blob/master/format/caff/caff.go
